backend:
  name: github
  repo: dublinhhh/website
  branch: main                  # branch to update (optional; defaults to master)
  api_root: https://api.github.com
  site_domain: cms.netlify.com  # cms.netlify.com for local development
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "assets/images" # Media files will be stored here in the repo

collections:

  - name: hareline
    label: Hareline
    folder: _hareline
    extension: frontmatter
    format: frontmatter
    identifier: name
    slug: "{{year}}-{{month}}-{{day}}|{{name}}"
    preview_path_date_field: date
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 'Time', name: 'time', widget: 'string', default: '19:30', required: false }
      - { label: 'End Date', name: 'end_date', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false,
          default: '', hint: 'Only for multi-day hash events', required: false }
      - { label: 'Hares', name: 'hares', widget: 'list', field: { label: Hares, name: hare, widget: 'string' } }
      - { label: 'Hash', name: hash, widget: 'select', options: [ 'Dublin H3', 'I ♥ Monday' ], required: false }
      - { label: 'Number', name: number, widget: 'number', value_type: 'int', required: false }
      - { label: 'Name', name: 'name', widget: 'string', required: false, hint: 'E.g.: Annual Shed Hash' }
      - { label: 'Map URL', name: 'map_url', widget: 'string', required: false }
      - { label: 'Directions URL', name: 'directions_url', widget: 'string', required: false }
      - { label: 'W3W', name: 'w3w', widget: 'string', required: false }
      - { label: 'Notes', name: 'body', widget: 'markdown', hint: 'Anything you want to add...' }

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Contacts'
        name: 'contact'
        file: 'contact.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Contacts' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'contact' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
